version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - desafionginx
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    image: mdvedovato/node

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./bancodados:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafionginx
    ports:
      - "3306:3306"

  nginx:
    build: ./nginx
    container_name: nginx
    image: mdvedovato/nginx
    networks:
      - desafionginx
    ports:
      - 8080:80
    depends_on:
      - app

networks:
  desafionginx:
    driver: bridge
